version: 0.0
os: linux   # Specify your operating system (linux or windows)

files:
  - source: /
    destination: /var/https:/github.com/paulherald/CCPipelines//index.html/DemoApp

permissions:
  - object: /var/https://github.com/paulherald/CCPipelines/index.html/Demoapp
    pattern: "**"
    owner: ec2-user
    group: www-data
    mode: 755

hooks:
  BeforeInstall:
    - timeout: 300
      runas: root

  AfterInstall:
    - timeout: 300
      runas: root

  ApplicationStart:
    - timeout: 300
      runas: root

  ValidateService:
    - location: ***.sh
      timeout: 60
      runas: root
